project:
  type: website

website:
  title: "Advent of Code 2022"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  sidebar: 
    style: "floating"
    search: true

format:
  html:
    theme: "darkly"
    css: styles.css
    toc: true

editor: visual

