project:
  type: website
  output-dir: "docs"

execute:
  freeze: auto

website:
  title: "Advent of Code 2022"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  sidebar: 
    style: "floating"
    search: true

format:
  html:
    theme: "darkly"
    include-in-header: google_font.html
    monofont: Fira Code
    toc: true

editor: visual

